package dao.mapper;

import dao.model.resource;
import dao.model.resourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface resourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Mon Apr 23 16:56:45 CST 2018
     */
    long countByExample(resourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Mon Apr 23 16:56:45 CST 2018
     */
    int deleteByExample(resourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Mon Apr 23 16:56:45 CST 2018
     */
    int insert(resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Mon Apr 23 16:56:45 CST 2018
     */
    int insertSelective(resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Mon Apr 23 16:56:45 CST 2018
     */
    List<resource> selectByExample(resourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Mon Apr 23 16:56:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") resource record, @Param("example") resourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Mon Apr 23 16:56:45 CST 2018
     */
    int updateByExample(@Param("record") resource record, @Param("example") resourceExample example);
}