package dao.mapper;

import dao.model.role_resource;
import dao.model.role_resourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface role_resourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbg.generated Mon Apr 23 16:56:45 CST 2018
     */
    long countByExample(role_resourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbg.generated Mon Apr 23 16:56:45 CST 2018
     */
    int deleteByExample(role_resourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbg.generated Mon Apr 23 16:56:45 CST 2018
     */
    int insert(role_resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbg.generated Mon Apr 23 16:56:45 CST 2018
     */
    int insertSelective(role_resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbg.generated Mon Apr 23 16:56:45 CST 2018
     */
    List<role_resource> selectByExample(role_resourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbg.generated Mon Apr 23 16:56:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") role_resource record, @Param("example") role_resourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbg.generated Mon Apr 23 16:56:45 CST 2018
     */
    int updateByExample(@Param("record") role_resource record, @Param("example") role_resourceExample example);
}