package dao.model;

import java.util.Date;

public class sysLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.id
     *
     * @mbg.generated Mon Apr 23 16:56:45 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.login_name
     *
     * @mbg.generated Mon Apr 23 16:56:45 CST 2018
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.role_name
     *
     * @mbg.generated Mon Apr 23 16:56:45 CST 2018
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.opt_content
     *
     * @mbg.generated Mon Apr 23 16:56:45 CST 2018
     */
    private String optContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.client_ip
     *
     * @mbg.generated Mon Apr 23 16:56:45 CST 2018
     */
    private String clientIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.create_time
     *
     * @mbg.generated Mon Apr 23 16:56:45 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.id
     *
     * @return the value of sys_log.id
     *
     * @mbg.generated Mon Apr 23 16:56:45 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.id
     *
     * @param id the value for sys_log.id
     *
     * @mbg.generated Mon Apr 23 16:56:45 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.login_name
     *
     * @return the value of sys_log.login_name
     *
     * @mbg.generated Mon Apr 23 16:56:45 CST 2018
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.login_name
     *
     * @param loginName the value for sys_log.login_name
     *
     * @mbg.generated Mon Apr 23 16:56:45 CST 2018
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.role_name
     *
     * @return the value of sys_log.role_name
     *
     * @mbg.generated Mon Apr 23 16:56:45 CST 2018
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.role_name
     *
     * @param roleName the value for sys_log.role_name
     *
     * @mbg.generated Mon Apr 23 16:56:45 CST 2018
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.opt_content
     *
     * @return the value of sys_log.opt_content
     *
     * @mbg.generated Mon Apr 23 16:56:45 CST 2018
     */
    public String getOptContent() {
        return optContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.opt_content
     *
     * @param optContent the value for sys_log.opt_content
     *
     * @mbg.generated Mon Apr 23 16:56:45 CST 2018
     */
    public void setOptContent(String optContent) {
        this.optContent = optContent == null ? null : optContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.client_ip
     *
     * @return the value of sys_log.client_ip
     *
     * @mbg.generated Mon Apr 23 16:56:45 CST 2018
     */
    public String getClientIp() {
        return clientIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.client_ip
     *
     * @param clientIp the value for sys_log.client_ip
     *
     * @mbg.generated Mon Apr 23 16:56:45 CST 2018
     */
    public void setClientIp(String clientIp) {
        this.clientIp = clientIp == null ? null : clientIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.create_time
     *
     * @return the value of sys_log.create_time
     *
     * @mbg.generated Mon Apr 23 16:56:45 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.create_time
     *
     * @param createTime the value for sys_log.create_time
     *
     * @mbg.generated Mon Apr 23 16:56:45 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}